#' process daylight saving date records
#'
#' This function processes the dataframe recording 2 daylight saving dates in 
#' each year: concatenate year-month-date, convert data types, calculate the day
#' after daylight saving day
#' 
#'
#' @param daylight_saving_table A dataframe with 3 columns recording daylight 
#' saving dates once in the spring, once in the fall:
#' Year, Spring (date-month), Fall(date-month)
#' @return daylight_saving_table dataframe after processing.
#' @examples
#' daylight_saving_process(your_dataframe)
daylight_saving_process <- function(daylight_saving_table)
{
  colnames(daylight_saving_table) <- c("Year", "Spring", "Fall")
  daylight_saving_table$Year <- as.character(daylight_saving_table$Year)
  daylight_saving_table$Spring <- ydm(paste(daylight_saving_table$Year, daylight_saving_table$Spring, sep = "-"), tz="America/Los_Angeles")
  daylight_saving_table$Fall <- ydm(paste(daylight_saving_table$Year, daylight_saving_table$Fall, sep = "-"), tz="America/Los_Angeles")
  daylight_saving_table$Year <- as.integer(daylight_saving_table$Year)
  daylight_saving_table <- daylight_saving_table[order(daylight_saving_table$Year),]
  daylight_saving_table$Spring_nextDay <- daylight_saving_table$Spring + days(1)
  daylight_saving_table$Fall_nextDay <- daylight_saving_table$Fall + days(1)
  return(daylight_saving_table)
}

#' Process file names
#' 
#' This function processes a vector of file names: trims white spaces, replaces 
#' slashes and spaces with underscores, and extracts date information. It then 
#' returns a data frame with original file names and extracted dates.
#' 
#' @param fileNames A character vector of file names.
#' @param col_name A string specifying the column name for the file names in the 
#' output data frame.
#' 
#' @return A data frame with original file names and extracted dates.
#' 
#' @examples
#' file_name_processing(c("feed/VR200715.DAT", "feed/VR200716.DAT"), "Feed_dir")
file_name_processing <- function(fileNames, col_name){
  file_name <- data.frame(fileNames)
  colnames(file_name) <- c(col_name)
  file_name_mod <- chartr("/ .", "___", trimws(file_name[,1]))
  date <- sapply(strsplit(file_name_mod, "_"), function(x) substring(x[length(x)-1], 3))
  cbind(file_name, date = date)
}

#' Compare feed and water file names
#' 
#' This function compares feed and water file names, and keeps only the file 
#' names that have both feed and water data available at the same time.
#' 
#' @param fileNames.f A character vector of feed file names.
#' @param fileNames.w A character vector of water file names.
#' 
#' @return A list with updated feed and water file names (dates with both feed 
#' and water data available at the same time).
#' 
#' @examples
#' compare_files(c("feed/VR200715.DAT", "feed/VR200716.DAT"), c("water/VW200715.DAT"))
compare_files <- function(fileNames.f, fileNames.w){
  feed_name <- file_name_processing(fileNames.f, "Feed_dir")
  wat_name <- file_name_processing(fileNames.w, "Drink_dir")
  compare_sheet <- merge(feed_name, wat_name, all = TRUE)
  compare_sheet <- compare_sheet[order(compare_sheet$date),]
  compare_sheet2 <- na.omit(compare_sheet)
  compare_sheet2$date <- ymd(compare_sheet2$date, tz="America/Los_Angeles")
  compare_sheet2
}

#' Get date range for this dataset
#' 
#' This function takes in a dataframe generated by compare_files() 
#' and calculates the date range based on the date column.
#' 
#' @param df A dataframe generated by compare_files().
#' 
#' @return A list with start date, end date, and date range string.
#' 
#' @examples
#' df <- compare_files(c("feed/VR200715.DAT", "feed/VR200716.DAT"), c("water/VW200715.DAT"))
#' get_date_range(df)
get_date_range <- function(df){
  # Check if the dataframe has a date column
  if(!"date" %in% names(df)){
    stop("The input dataframe does not have a date column.")
  }
  
  # Check if the dataframe has any rows
  if(nrow(df) == 0){
    print("Warning: The input dataframe does not have any rows.")
    return(list())
  }
  
  # Calculate start and end date
  start_date <- min(df$date)
  end_date <- max(df$date)
  
  # Generate date range string
  date_range <- ifelse((start_date != end_date), paste(start_date, end_date, sep = "_"), as.character(start_date))
  
  list(start_date = start_date, end_date = end_date, date_range = date_range)
}
