#' process daylight saving date records
#'
#' This function processes the dataframe recording 2 daylight saving dates in 
#' each year: concatenate year-month-date, convert data types, calculate the day
#' after daylight saving day
#' 
#'
#' @param daylight_saving_table A dataframe with 3 columns recording daylight 
#' saving dates once in the spring, once in the fall:
#' Year, Spring (date-month), Fall(date-month)
#' @return daylight_saving_table dataframe after processing.
#' @examples
#' daylight_saving_process(your_dataframe)
daylight_saving_process <- function(daylight_saving_table)
{
  colnames(daylight_saving_table) <- c("Year", "Spring", "Fall")
  daylight_saving_table$Year <- as.character(daylight_saving_table$Year)
  daylight_saving_table$Spring <- ydm(paste(daylight_saving_table$Year, daylight_saving_table$Spring, sep = "-"), tz="America/Los_Angeles")
  daylight_saving_table$Fall <- ydm(paste(daylight_saving_table$Year, daylight_saving_table$Fall, sep = "-"), tz="America/Los_Angeles")
  daylight_saving_table$Year <- as.integer(daylight_saving_table$Year)
  daylight_saving_table <- daylight_saving_table[order(daylight_saving_table$Year),]
  daylight_saving_table$Spring_nextDay <- daylight_saving_table$Spring + days(1)
  daylight_saving_table$Fall_nextDay <- daylight_saving_table$Fall + days(1)
  return(daylight_saving_table)
}

#' Process file names
#' 
#' This function processes a vector of file names: trims white spaces, replaces 
#' slashes and spaces with underscores, and extracts date information. It then 
#' returns a data frame with original file names and extracted dates.
#' 
#' @param fileNames A character vector of file names.
#' @param col_name A string specifying the column name for the file names in the 
#' output data frame.
#' 
#' @return A data frame with original file names and extracted dates.
#' 
#' @examples
#' file_name_processing(c("feed/VR200715.DAT", "feed/VR200716.DAT"), "Feed_dir")
file_name_processing <- function(fileNames, col_name){
  file_name <- data.frame(fileNames)
  colnames(file_name) <- c(col_name)
  file_name_mod <- chartr("/ .", "___", trimws(file_name[,1]))
  date <- sapply(strsplit(file_name_mod, "_"), function(x) substring(x[length(x)-1], 3))
  cbind(file_name, date = date)
}

#' Compare feed and water file names
#' 
#' This function compares feed and water file names, and keeps only the file 
#' names that have both feed and water data available at the same time.
#' 
#' @param fileNames.f A character vector of feed file names.
#' @param fileNames.w A character vector of water file names.
#' 
#' @return A list with updated feed and water file names (dates with both feed 
#' and water data available at the same time).
#' 
#' @examples
#' compare_files(c("feed/VR200715.DAT", "feed/VR200716.DAT"), c("water/VW200715.DAT"))
compare_files <- function(fileNames.f, fileNames.w){
  feed_name <- file_name_processing(fileNames.f, "Feed_dir")
  wat_name <- file_name_processing(fileNames.w, "Drink_dir")
  compare_sheet <- merge(feed_name, wat_name, all = TRUE)
  compare_sheet <- compare_sheet[order(compare_sheet$date),]
  compare_sheet2 <- na.omit(compare_sheet)
  compare_sheet2$date <- ymd(compare_sheet2$date, tz="America/Los_Angeles")
  compare_sheet2
}

#' Get date range for this dataset
#' 
#' This function takes in a dataframe generated by compare_files() 
#' and calculates the date range based on the date column.
#' 
#' @param df A dataframe generated by compare_files().
#' 
#' @return A list with start date, end date, and date range string.
#' 
#' @examples
#' df <- compare_files(c("feed/VR200715.DAT", "feed/VR200716.DAT"), c("water/VW200715.DAT"))
#' get_date_range(df)
get_date_range <- function(df){
  # Check if the dataframe has a date column
  if(!"date" %in% names(df)){
    stop("The input dataframe does not have a date column.")
  }
  
  # Check if the dataframe has any rows
  if(nrow(df) == 0){
    print("Warning: The input dataframe does not have any rows.")
    return(list())
  }
  
  # Calculate start and end date
  start_date <- min(df$date)
  end_date <- max(df$date)
  
  # Generate date range string
  date_range <- ifelse((start_date != end_date), paste(start_date, end_date, sep = "_"), as.character(start_date))
  
  list(start_date = start_date, end_date = end_date, date_range = date_range)
}


#' Remove specific cows from the dataframe
#'
#' This function filters out rows from the provided dataframe `df` 
#' that contain cows specified in the `cow_delete_list`.
#' 
#' @param df A dataframe containing a column named "Cow".
#' @param cow_delete_list A vector of cows to be deleted from `df`.
#'
#' @return A dataframe without the rows containing cows from `cow_delete_list`.
#'
#' @examples
#' \dontrun{
#' df <- data.frame(Cow = c("A", "B", "C", "D"), Value = c(1, 2, 3, 4))
#' cow_delete_list <- c("A", "C")
#' cow_delete(df, cow_delete_list)
#' }
cow_delete <- function(df, cow_delete_list) {
  to_delete <- df[which(df$Cow %in% cow_delete_list),]
  if (nrow(to_delete) != 0) {
    df_processed <- df[-which(df$Cow %in% cow_delete_list),]
    return(df_processed)
  } else {
    return(df)
  }
}


#' Delete rows with specific transponder ID
#'
#' @param df Data frame from which to delete rows.
#' @param transponder_delete_list List of transponder ID to delete.
#' @return Data frame with rows that contain certain trasponder ID deleted.
transponder_delete <- function(df, transponder_delete_list) {
  to_delete <- df[which(df$Transponder %in% transponder_delete_list), ]
  if (nrow(to_delete) != 0) {
    df[-which(df$Transponder %in% transponder_delete_list), ]
  } else {
    df
  }
}

#' Delete rows outside specific bin range
#'
#' @param df Data frame from which to delete rows.
#' @param min_bin Minimum bin ID to keep.
#' @param max_bin Maximum bin ID to keep.
#' @return Data frame with rows deleted.
bin_delete <- function(df, min_bin, max_bin) {
  df[df$Bin >= min_bin & df$Bin <= max_bin, ]
}

#' Process feeder data
#'
#' @param file_name File path for the feeder data.
#' @param coln Column names for the feeder data.
#' @param cow_delete_list List of cow values to delete.
#' @param feed_transponder_delete_list List of transponder values specific to feeder data to delete.
#' @param min_feed_bin Minimum feeder bin value to keep.
#' @param max_feed_Bin Maximum feeder bin value to keep.
#' @param feed_coln_to_keep Columns to keep in the feeder data.
#' @return Processed data frame for feeder.
process_feeder_data <- function(file_name, coln, cow_delete_list, feed_transponder_delete_list, min_feed_bin, max_feed_Bin, feed_coln_to_keep) {
  feeder = read.table(file_name, header = F, sep = ",")
  colnames(feeder) = coln
  feeder = cow_delete(feeder, cow_delete_list)
  feeder = transponder_delete(feeder, feed_transponder_delete_list)
  feeder = bin_delete(feeder, min_feed_bin, max_feed_Bin)
  feeder[, feed_coln_to_keep]
}

#' Process water data
#'
#' @param file_name File path for the water data.
#' @param coln_wat Column names for the water data.
#' @param cow_delete_list List of cow values to delete.
#' @param wat_transponder_delete_list List of transponder values specific to water data to delete.
#' @param min_wat_bin Minimum water bin value to keep.
#' @param max_wat_Bin Maximum water bin value to keep.
#' @param wat_coln_to_keep Columns to keep in the water data.
#' @return Processed data frame for water.
process_water_data <- function(file_name, coln_wat, cow_delete_list, wat_transponder_delete_list, min_wat_bin, max_wat_Bin, wat_coln_to_keep) {
  water = read.table(file_name, header = F, sep = ",")
  colnames(water) = coln_wat
  water = cow_delete(water, cow_delete_list)
  water = transponder_delete(water, wat_transponder_delete_list)
  water = bin_delete(water, min_wat_bin, max_wat_Bin)
  rename_water_bins(water[, wat_coln_to_keep], min_wat_bin, max_wat_Bin)
}

#' Rename water bins
#'
#' @param water_df Data frame of water data.
#' @param bin_id_add The number to add to bin IDs.
#' @param min_wat_bin Minimum water bin value for renaming.
#' @param max_wat_Bin Maximum water bin value for renaming.
#' @return Data frame with water bins renamed.
rename_water_bins <- function(water_df, bin_id_add, min_wat_bin, max_wat_Bin) {
  for (i in min_wat_bin:max_wat_Bin) {
    water_df$Bin[which(water_df$Bin == i)] = bin_id_add + i
  }
  water_df
}



